const PROJECTS = [

    {
        id: "melbourne-city-sector-ii",
        name: "Melbourne City Sector II",
        slug: "melbourne-city-sector-ii",
        type: "plot",
        location: "Kaldongri, Nagpur",
        description:
            "A thoughtfully planned residential development spread across 4 acres featuring 71 residential plots. Designed for families and investors seeking long-term growth and peaceful living.",
        details: [
            "71 Residential Plots spread over 4 Acres in Kaldongri, Nagpur",
            "NMRDA Sanctioned RL Status (100% Legal Clear Title & Bank Loan Approved)",
            "Wide paved asphalt roads with underground electrical & sewerage networks",
            "Prime position in Kaldongri corridor with direct connectivity to Wardha Road & Airport",
        ],
        specs: [
            { label: "Project Area", value: "4 Acres" },
            { label: "Total Plots", value: "71 Residential Plots" },
            { label: "Plot Sizes", value: "1,200 - 3,500 Sq. Ft." },
            { label: "Bank Loan", value: "Up to 80% Approved" },
            { label: "Approval Status", value: "NMRDA Sanctioned RL (Clear Title)" },
        ],
        highlights: [
            "71 Residential Plots",
            "4 Acre Development",
            "Lifestyle Amenities",
            "Excellent Investment Opportunity",
        ],
        amenities: [
            "European Style Entrance Gate",
            "Landscaped Gardens",
            "Children's Play Area",
            "Jogging Track",
            "Gazebos & Outdoor Seating",
            "Wide Tar & Cement Roads",
            "Sewerage Network & Electrical Infrastructure",
            "Street Lighting",
        ],
        acres: "4",
        totalUnits: "71",
        status: "ongoing",
        priceRange: "₹22 Lakh onward",
        image: "/images/project_melbourne_png_1780484693295.png",
        gallery: ["/images/project_melbourne_png_1780484693295.png"],
        coordinate: { x: 38, y: 72 },
        mapHotspot: "Kaldongri Highway Hub",
        phone: "+91 93732 33777",
    },

    {
        id: "canberra-city",
        name: "Canberra City",
        slug: "canberra-city",
        type: "plot",
        location: "Wardha Road Corridor, Nagpur",
        description:
            "Spread across 6 acres with 97 residential plots, Canberra City combines modern infrastructure, open spaces, and investment potential in a well-planned residential community.",
        details: [
            "6 acres of perfectly flat, elevated prime residential land",
            "97 Residential Plots with NMRDA Sanctioned Release Letter (RL)",
            "Wide 40ft & 30ft internal tar roads with green open spaces & storm water systems",
            "Individual water supply lines & underground electricity at every plot boundary",
        ],
        specs: [
            { label: "Project Area", value: "6 Acres" },
            { label: "Total Plots", value: "97 Residential Plots" },
            { label: "Internal Roads", value: "30ft & 40ft Broad Asphalt Avenues" },
            { label: "Bank Loan Support", value: "Pre-Approved Up to 80%" },
            { label: "Clear Title", value: "100% NMRDA RL Sanctioned" },
        ],
        highlights: [
            "97 Residential Plots",
            "6 Acre Development",
            "Green Open Spaces",
            "Premium Layout Planning",
        ],
        amenities: [
            "Grand Entrance Security Gate",
            "Landscaped Gardens & Open Green Spaces",
            "Gazebos & Outdoor Seating Areas",
            "Broad Walking & Jogging Tracks",
            "Storm Water & Drainage System",
            "24/7 Gated Security Patrol",
            "Wide Tar & Cement Roads",
        ],
        acres: "6",
        totalUnits: "97",
        status: "ongoing",
        priceRange: "₹30 Lakh onward",
        image: "/images/project_canberra_png_1780484709897.png",
        gallery: ["/images/project_canberra_png_1780484709897.png"],
        coordinate: { x: 25, y: 58 },
        mapHotspot: "Wardha Road Smart Belt",
        phone: "+91 93732 33777",
    },

    {
        id: "shraddha-bhakti-avenue",
        name: "Shraddha Bhakti Avenue",
        slug: "shraddha-bhakti-avenue",
        type: "apartment",
        location: "Besa, Nagpur",
        description:
            "Experience luxury living with spacious 3 BHK residences designed for modern families seeking comfort, elegance, and convenience.",
        details: [
            "7 Storey Premium Building in Besa, Nagpur",
            "Singular Opulent 3 BHK Apartments (2106 Sq. Ft. Super Built-Up Area)",
            "Prime Residential Location with easy connectivity",
            "Luxury living with modern facilities",
        ],
        specs: [
            { label: "Configuration", value: "3 BHK Homes" },
            { label: "Super Built-Up Area", value: "2106 Sq. Ft." },
            { label: "Floors", value: "7 Storey Premium Building" },
            { label: "Location", value: "Prime Besa, Nagpur" },
        ],
        highlights: [
            "2106 Sq. Ft. Super Built-Up Area",
            "7 Storey Premium Building",
            "Spacious 3 BHK Homes",
            "Prime Residential Location",
        ],
        amenities: [
            "Elevator & Power Backup",
            "Kids Play Area & Landscaped Open Spaces",
            "Fire Safety Infrastructure",
            "Covered Parking & Security",
        ],
        acres: "Boutique Project",
        totalUnits: "28",
        status: "completed",
        priceRange: "₹85 Lakh onward",
        image: "/images/project_shraddha_png_1780484729700.png",
        gallery: ["/images/project_shraddha_png_1780484729700.png"],
        coordinate: { x: 52, y: 40 },
        mapHotspot: "Besa Square Premium Belt",
        phone: "+91 93716 12666",
    },

    {
        id: "perth-city",
        name: "Perth City",
        slug: "perth-city",
        type: "plot",
        location: "Kharsoli, Nagpur",
        description: "Premium plotted development in Kharsoli with modern gated amenities.",
        details: ["NMRDA Approved", "Wide Roads", "Underground Utilities", "High ROI"],
        specs: [
            { label: "Area", value: "9 Acres" },
            { label: "Plots", value: "126+" },
        ],
        highlights: [
            "Premium Layout",
            "Gated Community",
            "Prime Location",
            "Investment Opportunity",
        ],
        amenities: ["Garden", "Security", "LED Lights", "Road Network"],
        acres: "9",
        totalUnits: "126+",
        status: "ongoing",
        priceRange: "Price on Request",
        image: "/images/project_melbourne_png_1780484693295.png",
        gallery: ["/images/project_melbourne_png_1780484693295.png"],
        coordinate: { x: 72, y: 38 },
        mapHotspot: "Kharsoli Growth Zone",
        phone: "+91 93732 33777",
    },

    {
        id: "kharsoli-township",
        name: "Kharsoli Township Project",
        slug: "kharsoli-township",
        type: "upcoming",
        location: "Kharsoli, Nagpur",
        description:
            "A premium township development spread across 9 acres featuring 126 residential plots designed for future-ready living.",
        details: [
            "9 Acres Township Development in Kharsoli",
            "126 Residential Plots",
            "Planned Residential Community",
            "Wide Internal Roads & Modern Infrastructure",
        ],
        specs: [
            { label: "Area", value: "9 Acres" },
            { label: "Plots", value: "126 Residential Plots" },
            { label: "Status", value: "Upcoming Pre-Launch" },
        ],
        highlights: [
            "Planned Residential Community",
            "Wide Internal Roads",
            "Modern Infrastructure",
            "Future Growth Potential",
        ],
        amenities: [
            "Wide Internal Roads",
            "Landscaped Green Spaces",
            "Electrical & Underground Drainage",
            "Street Lighting",
        ],
        acres: "9",
        totalUnits: "126",
        status: "upcoming",
        priceRange: "Coming Soon",
        image: "/images/project_melbourne_png_1780484693295.png",
        gallery: ["/images/project_melbourne_png_1780484693295.png"],
        coordinate: { x: 70, y: 35 },
        mapHotspot: "Kharsoli",
        phone: "+91 93732 33777",
    },

    {
        id: "mega-township-project",
        name: "Mega Township Project",
        slug: "mega-township-project",
        type: "upcoming",
        location: "Nagpur Growth Corridor",
        description:
            "A landmark 60+ acre development featuring over 1000 residential plots designed to become one of Nagpur's most promising residential destinations.",
        details: [
            "Landmark 60+ Acre Mega Township",
            "1000+ Residential Plots",
            "Comprehensive Infrastructure & Open Green Spaces",
            "Long-Term Appreciation Potential",
        ],
        specs: [
            { label: "Township Area", value: "60+ Acres" },
            { label: "Total Plots", value: "1000+ Residential Plots" },
            { label: "Status", value: "Upcoming Flagship Pre-Launch" },
        ],
        highlights: [
            "60+ Acre Township",
            "1000+ Residential Plots",
            "Comprehensive Infrastructure",
            "Long-Term Appreciation Potential",
        ],
        amenities: [
            "Grand Entrance Arch",
            "Broad Avenues & Internal Roads",
            "Parks & Recreation Hubs",
            "Underground Utilities & Street Lights",
        ],
        acres: "60+",
        totalUnits: "1000+",
        status: "upcoming",
        priceRange: "Price on Request",
        image: "/images/project_melbourne_png_1780484693295.png",
        gallery: ["/images/project_melbourne_png_1780484693295.png"],
        coordinate: { x: 72, y: 38 },
        mapHotspot: "Nagpur Growth Corridor",
        phone: "+91 93732 33777",
    },
];

export default PROJECTS;
